version: '3.8'

services:
  app:
    image: 'my_custom_php:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./src/:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: secret
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: